mod instructions;
pub mod interrupts;
mod operand;
mod registers;

use self::instructions::{go, step};
use self::interrupts::{Interrupts, JOYPAD, SERIAL, STAT, TIMER, VBLANK};
use self::operand::{Cond, Direct8, Direct16, Imm8, Imm16, Indirect, Reg8, Reg16};
use self::registers::Registers;
use super::peripherals::Peripherals;
use ::std::sync::atomic::{AtomicU8, AtomicU16, Ordering::Relaxed};

#[derive(Default)]
struct Ctx {
    opcode: u8,
    cb: bool,
    int: bool,
}

pub struct Cpu {
    regs: Registers,
    pub interrupts: Interrupts,
    ctx: Ctx,
}

impl Cpu {
    pub fn new() -> Self {
        Cpu {
            regs: Registers::default(),
            interrupts: Interrupts::default(),
            ctx: Ctx::default(),
        }
    }

    pub fn emulate_cycle(&mut self, bus: &mut Peripherals) {
        if self.ctx.int {
            self.call_isr(bus);
            return;
        }
        self.decode(bus);
    }

    // todo: もっとわかりやすく
    pub fn fetch(&mut self, bus: &Peripherals) {
        self.ctx.opcode = bus.read(self.regs.pc); // 割り込み時もreadする必要がある？
        if self.interrupts.ime && self.interrupts.get_interrupts() > 0 {
            self.ctx.int = true;
        } else {
            self.regs.pc = self.regs.pc.wrapping_add(1);
            self.ctx.int = false;
        }
        self.ctx.cb = false;
    }

    pub fn decode(&mut self, bus: &mut Peripherals) {
        if self.ctx.cb {
            self.cb_decode(bus);
            return;
        }
        match self.ctx.opcode {
            0x00 => self.nop(bus),
            0x01 => self.ld16(bus, Reg16::BC, Imm16),
            0x02 => self.ld(bus, Indirect::BC, Reg8::A),
            0x03 => self.inc16(bus, Reg16::BC),
            0x04 => self.inc(bus, Reg8::B),
            0x05 => self.dec(bus, Reg8::B),
            0x06 => self.ld(bus, Reg8::B, Imm8),
            0x07 => self.rlca(bus),
            0x08 => self.ld16(bus, Direct16, Reg16::SP),
            // 0x09
            0x0a => self.ld(bus, Reg8::A, Indirect::BC),
            0x0b => self.dec16(bus, Reg16::BC),
            0x0c => self.inc(bus, Reg8::C),
            0x0d => self.dec(bus, Reg8::C),
            0x0e => self.ld(bus, Reg8::C, Imm8),
            0x0f => self.rrca(bus),
            0x10 => self.stop(bus),
            0x11 => self.ld16(bus, Reg16::DE, Imm16),
            0x12 => self.ld(bus, Indirect::DE, Reg8::A),
            0x13 => self.inc16(bus, Reg16::DE),
            0x14 => self.inc(bus, Reg8::D),
            0x15 => self.dec(bus, Reg8::D),
            0x16 => self.ld(bus, Reg8::D, Imm8),
            0x17 => self.rla(bus),
            0x18 => self.jr(bus),
            // 0x19
            0x1a => self.ld(bus, Reg8::A, Indirect::DE),
            0x1b => self.dec16(bus, Reg16::DE),
            0x1c => self.inc(bus, Reg8::E),
            0x1d => self.dec(bus, Reg8::E),
            0x1e => self.ld(bus, Reg8::E, Imm8),
            0x1f => self.rra(bus),
            0x20 => self.jr_c(bus, Cond::NZ),
            0x21 => self.ld16(bus, Reg16::HL, Imm16),
            0x22 => self.ld(bus, Indirect::HLI, Reg8::A),
            0x23 => self.inc16(bus, Reg16::HL),
            0x24 => self.inc(bus, Reg8::H),
            0x25 => self.dec(bus, Reg8::H),
            0x26 => self.ld(bus, Reg8::H, Imm8),
            0x27 => self.daa(bus),
            0x28 => self.jr_c(bus, Cond::Z),
            // 0x29
            0x2a => self.ld(bus, Reg8::A, Indirect::HLI),
            0x2b => self.dec16(bus, Reg16::HL),
            0x2c => self.inc(bus, Reg8::L),
            0x2d => self.dec(bus, Reg8::L),
            0x2e => self.ld(bus, Reg8::L, Imm8),
            // 0x2f
            0x30 => self.jr_c(bus, Cond::NC),
            0x31 => self.ld16(bus, Reg16::SP, Imm16),
            0x32 => self.ld(bus, Indirect::HLD, Reg8::A),
            0x33 => self.inc16(bus, Reg16::SP),
            0x34 => self.inc16(bus, Reg16::HL),
            0x35 => self.dec16(bus, Reg16::HL),
            0x36 => self.ld16(bus, Reg16::HL, Imm16),
            0x37 => self.scf(bus),
            0x38 => self.jr_c(bus, Cond::C),
            // 0x39
            0x3a => self.ld(bus, Reg8::A, Indirect::HLD),
            0x3b => self.dec16(bus, Reg16::SP),
            0x3c => self.inc(bus, Reg8::A),
            0x3d => self.dec(bus, Reg8::A),
            0x3e => self.ld(bus, Reg8::A, Imm8),
            0x3f => self.ccf(bus),
            0x40 => self.ld(bus, Reg8::B, Reg8::B),
            0x41 => self.ld(bus, Reg8::B, Reg8::C),
            0x42 => self.ld(bus, Reg8::B, Reg8::D),
            0x43 => self.ld(bus, Reg8::B, Reg8::E),
            0x44 => self.ld(bus, Reg8::B, Reg8::H),
            0x45 => self.ld(bus, Reg8::B, Reg8::L),
            0x46 => self.ld(bus, Reg8::B, Indirect::HL),
            0x47 => self.ld(bus, Reg8::B, Reg8::A),
            0x48 => self.ld(bus, Reg8::C, Reg8::B),
            0x49 => self.ld(bus, Reg8::C, Reg8::C),
            0x4a => self.ld(bus, Reg8::C, Reg8::D),
            0x4b => self.ld(bus, Reg8::C, Reg8::E),
            0x4c => self.ld(bus, Reg8::C, Reg8::H),
            0x4d => self.ld(bus, Reg8::C, Reg8::L),
            0x4e => self.ld(bus, Reg8::C, Indirect::HL),
            0x4f => self.ld(bus, Reg8::C, Reg8::A),
            0x50 => self.ld(bus, Reg8::D, Reg8::B),
            0x51 => self.ld(bus, Reg8::D, Reg8::C),
            0x52 => self.ld(bus, Reg8::D, Reg8::D),
            0x53 => self.ld(bus, Reg8::D, Reg8::E),
            0x54 => self.ld(bus, Reg8::D, Reg8::H),
            0x55 => self.ld(bus, Reg8::D, Reg8::L),
            0x56 => self.ld(bus, Reg8::D, Indirect::HL),
            0x57 => self.ld(bus, Reg8::D, Reg8::A),
            0x58 => self.ld(bus, Reg8::E, Reg8::B),
            0x59 => self.ld(bus, Reg8::E, Reg8::C),
            0x5a => self.ld(bus, Reg8::E, Reg8::D),
            0x5b => self.ld(bus, Reg8::E, Reg8::E),
            0x5c => self.ld(bus, Reg8::E, Reg8::H),
            0x5d => self.ld(bus, Reg8::E, Reg8::L),
            0x5e => self.ld(bus, Reg8::E, Indirect::HL),
            0x5f => self.ld(bus, Reg8::E, Reg8::A),
            0x60 => self.ld(bus, Reg8::H, Reg8::B),
            0x61 => self.ld(bus, Reg8::H, Reg8::C),
            0x62 => self.ld(bus, Reg8::H, Reg8::D),
            0x63 => self.ld(bus, Reg8::H, Reg8::E),
            0x64 => self.ld(bus, Reg8::H, Reg8::H),
            0x65 => self.ld(bus, Reg8::H, Reg8::L),
            0x66 => self.ld(bus, Reg8::H, Indirect::HL),
            0x67 => self.ld(bus, Reg8::H, Reg8::A),
            0x68 => self.ld(bus, Reg8::L, Reg8::B),
            0x69 => self.ld(bus, Reg8::L, Reg8::C),
            0x6a => self.ld(bus, Reg8::L, Reg8::D),
            0x6b => self.ld(bus, Reg8::L, Reg8::E),
            0x6c => self.ld(bus, Reg8::L, Reg8::H),
            0x6d => self.ld(bus, Reg8::L, Reg8::L),
            0x6e => self.ld(bus, Reg8::L, Indirect::HL),
            0x6f => self.ld(bus, Reg8::L, Reg8::A),
            0x70 => self.ld(bus, Indirect::HL, Reg8::B),
            0x71 => self.ld(bus, Indirect::HL, Reg8::C),
            0x72 => self.ld(bus, Indirect::HL, Reg8::D),
            0x73 => self.ld(bus, Indirect::HL, Reg8::E),
            0x74 => self.ld(bus, Indirect::HL, Reg8::H),
            0x75 => self.ld(bus, Indirect::HL, Reg8::L),
            0x76 => self.halt(bus),
            0x77 => self.ld(bus, Indirect::HL, Reg8::A),
            0x78 => self.ld(bus, Reg8::A, Reg8::B),
            0x79 => self.ld(bus, Reg8::A, Reg8::C),
            0x7a => self.ld(bus, Reg8::A, Reg8::D),
            0x7b => self.ld(bus, Reg8::A, Reg8::E),
            0x7c => self.ld(bus, Reg8::A, Reg8::H),
            0x7d => self.ld(bus, Reg8::A, Reg8::L),
            0x7e => self.ld(bus, Reg8::A, Indirect::HL),
            0x7f => self.ld(bus, Reg8::A, Reg8::A),
            0x80 => self.add(bus, Reg8::B),
            0x81 => self.add(bus, Reg8::C),
            0x82 => self.add(bus, Reg8::D),
            0x83 => self.add(bus, Reg8::E),
            0x84 => self.add(bus, Reg8::H),
            0x85 => self.add(bus, Reg8::L),
            0x86 => self.add(bus, Indirect::HL),
            0x87 => self.add(bus, Reg8::A),
            0x88 => self.adc(bus, Reg8::B),
            0x89 => self.adc(bus, Reg8::C),
            0x8a => self.adc(bus, Reg8::D),
            0x8b => self.adc(bus, Reg8::E),
            0x8c => self.adc(bus, Reg8::H),
            0x8d => self.adc(bus, Reg8::L),
            0x8e => self.adc(bus, Indirect::HL),
            0x8f => self.adc(bus, Reg8::A),
            0x90 => self.sub(bus, Reg8::B),
            0x91 => self.sub(bus, Reg8::C),
            0x92 => self.sub(bus, Reg8::D),
            0x93 => self.sub(bus, Reg8::E),
            0x94 => self.sub(bus, Reg8::H),
            0x95 => self.sub(bus, Reg8::L),
            0x96 => self.sub(bus, Indirect::HL),
            0x97 => self.sbc(bus, Reg8::A),
            0x98 => self.sbc(bus, Reg8::B),
            0x99 => self.sbc(bus, Reg8::C),
            0x9a => self.sbc(bus, Reg8::D),
            0x9b => self.sbc(bus, Reg8::E),
            0x9c => self.sbc(bus, Reg8::H),
            0x9d => self.sbc(bus, Reg8::L),
            0x9e => self.sbc(bus, Indirect::HL),
            0xa0 => self.and(bus, Reg8::B),
            0xa1 => self.and(bus, Reg8::C),
            0xa2 => self.and(bus, Reg8::D),
            0xa3 => self.and(bus, Reg8::E),
            0xa4 => self.and(bus, Reg8::H),
            0xa5 => self.and(bus, Reg8::L),
            0xa6 => self.and(bus, Indirect::HL),
            0xa7 => self.and(bus, Reg8::A),
            0xa8 => self.xor(bus, Reg8::B),
            0xa9 => self.xor(bus, Reg8::C),
            0xaa => self.xor(bus, Reg8::D),
            0xab => self.xor(bus, Reg8::E),
            0xac => self.xor(bus, Reg8::H),
            0xad => self.xor(bus, Reg8::L),
            0xae => self.xor(bus, Indirect::HL),
            0xaf => self.xor(bus, Reg8::A),
            0xb0 => self.or(bus, Reg8::B),
            0xb1 => self.or(bus, Reg8::C),
            0xb2 => self.or(bus, Reg8::D),
            0xb3 => self.or(bus, Reg8::E),
            0xb4 => self.or(bus, Reg8::H),
            0xb5 => self.or(bus, Reg8::L),
            0xb6 => self.or(bus, Indirect::HL),
            0xb7 => self.or(bus, Reg8::A),
            0xb8 => self.cp(bus, Reg8::B),
            0xb9 => self.cp(bus, Reg8::C),
            0xba => self.cp(bus, Reg8::D),
            0xbb => self.cp(bus, Reg8::E),
            0xbc => self.cp(bus, Reg8::H),
            0xbd => self.cp(bus, Reg8::L),
            0xbe => self.cp(bus, Indirect::HL),
            0xbf => self.cp(bus, Reg8::A),
            0xc0 => self.retc(bus, Cond::NZ),
            0xc1 => self.pop(bus, Reg16::BC),
            0xc2 => self.jpc(bus, Cond::NZ),
            0xc3 => self.jp(bus),
            0xc4 => self.callc(bus, Cond::NZ),
            0xc5 => self.push(bus, Reg16::BC),
            // 0xc6
            0xc7 => self.rst(bus, 0x00),
            0xc8 => self.retc(bus, Cond::Z),
            0xc9 => self.ret(bus),
            0xca => self.jpc(bus, Cond::Z),
            0xcb => self.cb_prefixed(bus),
            0xcc => self.callc(bus, Cond::Z),
            0xcd => self.call(bus),
            // 0xce
            0xcf => self.rst(bus, 0x08),
            0xd0 => self.retc(bus, Cond::NC),
            0xd1 => self.pop(bus, Reg16::DE),
            0xd2 => self.jpc(bus, Cond::NC),
            // 0xd3
            0xd4 => self.callc(bus, Cond::NC),
            0xd5 => self.push(bus, Reg16::DE),
            // 0xd6
            0xd7 => self.rst(bus, 0x10),
            0xd8 => self.retc(bus, Cond::C),
            0xd9 => self.reti(bus),
            0xda => self.jpc(bus, Cond::C),
            // 0xdb
            0xdc => self.callc(bus, Cond::C),
            // 0xdd
            // 0xde
            0xdf => self.rst(bus, 0x18),
            0xe0 => self.ld(bus, Direct8::DFF, Reg8::A),
            0xe1 => self.pop(bus, Reg16::HL),
            0xe2 => self.ld(bus, Indirect::CFF, Reg8::A),
            // 0xe3
            // 0xe4
            0xe5 => self.push(bus, Reg16::HL),
            // 0xe6
            0xe7 => self.rst(bus, 0x20),
            // 0xe8
            0xe9 => self.jphl(bus),
            0xea => self.ld(bus, Direct8::D, Reg8::A),
            // 0xeb
            // 0xec
            // 0xed
            // 0xee
            0xef => self.rst(bus, 0x28),
            0xf0 => self.ld(bus, Reg8::A, Direct8::DFF),
            0xf1 => self.pop(bus, Reg16::AF),
            0xf2 => self.ld(bus, Reg8::A, Indirect::CFF),
            0xf3 => self.di(bus),
            // 0xf4
            0xf5 => self.push(bus, Reg16::AF),
            // 0xf6
            0xf7 => self.rst(bus, 0x30),
            // 0xf8
            // 0xf9
            0xfa => self.ld(bus, Reg8::A, Direct8::D),
            0xfb => self.ei(bus),
            // 0xfc
            // 0xfd
            0xfe => self.cp(bus, Imm8),
            0xff => self.rst(bus, 0x38),
            _ => panic!("Not implemented: {:02x}", self.ctx.opcode),
        }
    }

    pub fn cb_decode(&mut self, bus: &mut Peripherals) {
        match self.ctx.opcode {
            0x00 => self.rlc(bus, Reg8::B),
            0x01 => self.rlc(bus, Reg8::C),
            0x02 => self.rlc(bus, Reg8::D),
            0x03 => self.rlc(bus, Reg8::E),
            0x04 => self.rlc(bus, Reg8::H),
            0x05 => self.rlc(bus, Reg8::L),
            0x06 => self.rlc(bus, Indirect::HL),
            0x07 => self.rlc(bus, Reg8::A),
            0x08 => self.rrc(bus, Reg8::B),
            0x09 => self.rrc(bus, Reg8::C),
            0x0a => self.rrc(bus, Reg8::D),
            0x0b => self.rrc(bus, Reg8::E),
            0x0c => self.rrc(bus, Reg8::H),
            0x0d => self.rrc(bus, Reg8::L),
            0x0e => self.rrc(bus, Indirect::HL),
            0x0f => self.rrc(bus, Reg8::A),
            0x10 => self.rl(bus, Reg8::B),
            0x11 => self.rl(bus, Reg8::C),
            0x12 => self.rl(bus, Reg8::D),
            0x13 => self.rl(bus, Reg8::E),
            0x14 => self.rl(bus, Reg8::H),
            0x15 => self.rl(bus, Reg8::L),
            0x16 => self.rl(bus, Indirect::HL),
            0x17 => self.rl(bus, Reg8::A),
            0x18 => self.rr(bus, Reg8::B),
            0x19 => self.rr(bus, Reg8::C),
            0x1a => self.rr(bus, Reg8::D),
            0x1b => self.rr(bus, Reg8::E),
            0x1c => self.rr(bus, Reg8::H),
            0x1d => self.rr(bus, Reg8::L),
            0x1e => self.rr(bus, Indirect::HL),
            0x1f => self.rr(bus, Reg8::A),
            0x20 => self.sla(bus, Reg8::B),
            0x21 => self.sla(bus, Reg8::C),
            0x22 => self.sla(bus, Reg8::D),
            0x23 => self.sla(bus, Reg8::E),
            0x24 => self.sla(bus, Reg8::H),
            0x25 => self.sla(bus, Reg8::L),
            0x26 => self.sla(bus, Indirect::HL),
            0x27 => self.sla(bus, Reg8::A),
            0x28 => self.sra(bus, Reg8::B),
            0x29 => self.sra(bus, Reg8::C),
            0x2a => self.sra(bus, Reg8::D),
            0x2b => self.sra(bus, Reg8::E),
            0x2c => self.sra(bus, Reg8::H),
            0x2d => self.sra(bus, Reg8::L),
            0x2e => self.sra(bus, Indirect::HL),
            0x2f => self.sra(bus, Reg8::A),
            0x30 => self.swap(bus, Reg8::B),
            0x31 => self.swap(bus, Reg8::C),
            0x32 => self.swap(bus, Reg8::D),
            0x33 => self.swap(bus, Reg8::E),
            0x34 => self.swap(bus, Reg8::H),
            0x35 => self.swap(bus, Reg8::L),
            0x36 => self.swap(bus, Indirect::HL),
            0x37 => self.swap(bus, Reg8::A),
            0x38 => self.srl(bus, Reg8::B),
            0x39 => self.srl(bus, Reg8::C),
            0x3a => self.srl(bus, Reg8::D),
            0x3b => self.srl(bus, Reg8::E),
            0x3c => self.srl(bus, Reg8::H),
            0x3d => self.srl(bus, Reg8::L),
            0x3e => self.srl(bus, Indirect::HL),
            0x3f => self.srl(bus, Reg8::A),

            0x40 => self.bit(bus, 0, Reg8::B),
            0x41 => self.bit(bus, 0, Reg8::C),
            0x42 => self.bit(bus, 0, Reg8::D),
            0x43 => self.bit(bus, 0, Reg8::E),
            0x44 => self.bit(bus, 0, Reg8::H),
            0x45 => self.bit(bus, 0, Reg8::L),
            0x46 => self.bit(bus, 0, Indirect::HL),
            0x47 => self.bit(bus, 0, Reg8::A),
            0x48 => self.bit(bus, 1, Reg8::B),
            0x49 => self.bit(bus, 1, Reg8::C),
            0x4a => self.bit(bus, 1, Reg8::D),
            0x4b => self.bit(bus, 1, Reg8::E),
            0x4c => self.bit(bus, 1, Reg8::H),
            0x4d => self.bit(bus, 1, Reg8::L),
            0x4e => self.bit(bus, 1, Indirect::HL),
            0x4f => self.bit(bus, 1, Reg8::A),
            0x50 => self.bit(bus, 2, Reg8::B),
            0x51 => self.bit(bus, 2, Reg8::C),
            0x52 => self.bit(bus, 2, Reg8::D),
            0x53 => self.bit(bus, 2, Reg8::E),
            0x54 => self.bit(bus, 2, Reg8::H),
            0x55 => self.bit(bus, 2, Reg8::L),
            0x56 => self.bit(bus, 2, Indirect::HL),
            0x57 => self.bit(bus, 2, Reg8::A),
            0x58 => self.bit(bus, 3, Reg8::B),
            0x59 => self.bit(bus, 3, Reg8::C),
            0x5a => self.bit(bus, 3, Reg8::D),
            0x5b => self.bit(bus, 3, Reg8::E),
            0x5c => self.bit(bus, 3, Reg8::H),
            0x5d => self.bit(bus, 3, Reg8::L),
            0x5e => self.bit(bus, 3, Indirect::HL),
            0x5f => self.bit(bus, 3, Reg8::A),
            0x60 => self.bit(bus, 4, Reg8::B),
            0x61 => self.bit(bus, 4, Reg8::C),
            0x62 => self.bit(bus, 4, Reg8::D),
            0x63 => self.bit(bus, 4, Reg8::E),
            0x64 => self.bit(bus, 4, Reg8::H),
            0x65 => self.bit(bus, 4, Reg8::L),
            0x66 => self.bit(bus, 4, Indirect::HL),
            0x67 => self.bit(bus, 4, Reg8::A),
            0x68 => self.bit(bus, 5, Reg8::B),
            0x69 => self.bit(bus, 5, Reg8::C),
            0x6a => self.bit(bus, 5, Reg8::D),
            0x6b => self.bit(bus, 5, Reg8::E),
            0x6c => self.bit(bus, 5, Reg8::H),
            0x6d => self.bit(bus, 5, Reg8::L),
            0x6e => self.bit(bus, 5, Indirect::HL),
            0x6f => self.bit(bus, 5, Reg8::A),
            0x70 => self.bit(bus, 6, Reg8::B),
            0x71 => self.bit(bus, 6, Reg8::C),
            0x72 => self.bit(bus, 6, Reg8::D),
            0x73 => self.bit(bus, 6, Reg8::E),
            0x74 => self.bit(bus, 6, Reg8::H),
            0x75 => self.bit(bus, 6, Reg8::L),
            0x76 => self.bit(bus, 6, Indirect::HL),
            0x77 => self.bit(bus, 6, Reg8::A),
            0x78 => self.bit(bus, 7, Reg8::B),
            0x79 => self.bit(bus, 7, Reg8::C),
            0x7a => self.bit(bus, 7, Reg8::D),
            0x7b => self.bit(bus, 7, Reg8::E),
            0x7c => self.bit(bus, 7, Reg8::H),
            0x7d => self.bit(bus, 7, Reg8::L),
            0x7e => self.bit(bus, 7, Indirect::HL),
            0x7f => self.bit(bus, 7, Reg8::A),
            0x80 => self.res(bus, 0, Reg8::B),
            0x81 => self.res(bus, 0, Reg8::C),
            0x82 => self.res(bus, 0, Reg8::D),
            0x83 => self.res(bus, 0, Reg8::E),
            0x84 => self.res(bus, 0, Reg8::H),
            0x85 => self.res(bus, 0, Reg8::L),
            0x86 => self.res(bus, 0, Indirect::HL),
            0x87 => self.res(bus, 0, Reg8::A),
            0x88 => self.res(bus, 1, Reg8::B),
            0x89 => self.res(bus, 1, Reg8::C),
            0x8a => self.res(bus, 1, Reg8::D),
            0x8b => self.res(bus, 1, Reg8::E),
            0x8c => self.res(bus, 1, Reg8::H),
            0x8d => self.res(bus, 1, Reg8::L),
            0x8e => self.res(bus, 1, Indirect::HL),
            0x8f => self.res(bus, 1, Reg8::A),
            0x90 => self.res(bus, 2, Reg8::B),
            0x91 => self.res(bus, 2, Reg8::C),
            0x92 => self.res(bus, 2, Reg8::D),
            0x93 => self.res(bus, 2, Reg8::E),
            0x94 => self.res(bus, 2, Reg8::H),
            0x95 => self.res(bus, 2, Reg8::L),
            0x96 => self.res(bus, 2, Indirect::HL),
            0x97 => self.res(bus, 2, Reg8::A),
            0x98 => self.res(bus, 3, Reg8::B),
            0x99 => self.res(bus, 3, Reg8::C),
            0x9a => self.res(bus, 3, Reg8::D),
            0x9b => self.res(bus, 3, Reg8::E),
            0x9c => self.res(bus, 3, Reg8::H),
            0x9d => self.res(bus, 3, Reg8::L),
            0x9e => self.res(bus, 3, Indirect::HL),
            0x9f => self.res(bus, 3, Reg8::A),
            0xa0 => self.res(bus, 4, Reg8::B),
            0xa1 => self.res(bus, 4, Reg8::C),
            0xa2 => self.res(bus, 4, Reg8::D),
            0xa3 => self.res(bus, 4, Reg8::E),
            0xa4 => self.res(bus, 4, Reg8::H),
            0xa5 => self.res(bus, 4, Reg8::L),
            0xa6 => self.res(bus, 4, Indirect::HL),
            0xa7 => self.res(bus, 4, Reg8::A),
            0xa8 => self.res(bus, 5, Reg8::B),
            0xa9 => self.res(bus, 5, Reg8::C),
            0xaa => self.res(bus, 5, Reg8::D),
            0xab => self.res(bus, 5, Reg8::E),
            0xac => self.res(bus, 5, Reg8::H),
            0xad => self.res(bus, 5, Reg8::L),
            0xae => self.res(bus, 5, Indirect::HL),
            0xaf => self.res(bus, 5, Reg8::A),
            0xb0 => self.res(bus, 6, Reg8::B),
            0xb1 => self.res(bus, 6, Reg8::C),
            0xb2 => self.res(bus, 6, Reg8::D),
            0xb3 => self.res(bus, 6, Reg8::E),
            0xb4 => self.res(bus, 6, Reg8::H),
            0xb5 => self.res(bus, 6, Reg8::L),
            0xb6 => self.res(bus, 6, Indirect::HL),
            0xb7 => self.res(bus, 6, Reg8::A),
            0xb8 => self.res(bus, 7, Reg8::B),
            0xb9 => self.res(bus, 7, Reg8::C),
            0xba => self.res(bus, 7, Reg8::D),
            0xbb => self.res(bus, 7, Reg8::E),
            0xbc => self.res(bus, 7, Reg8::H),
            0xbd => self.res(bus, 7, Reg8::L),
            0xbe => self.res(bus, 7, Indirect::HL),
            0xbf => self.res(bus, 7, Reg8::A),
            0xc0 => self.set(bus, 0, Reg8::B),
            0xc1 => self.set(bus, 0, Reg8::C),
            0xc2 => self.set(bus, 0, Reg8::D),
            0xc3 => self.set(bus, 0, Reg8::E),
            0xc4 => self.set(bus, 0, Reg8::H),
            0xc5 => self.set(bus, 0, Reg8::L),
            0xc6 => self.set(bus, 0, Indirect::HL),
            0xc7 => self.set(bus, 0, Reg8::A),
            0xc8 => self.set(bus, 1, Reg8::B),
            0xc9 => self.set(bus, 1, Reg8::C),
            0xca => self.set(bus, 1, Reg8::D),
            0xcb => self.set(bus, 1, Reg8::E),
            0xcc => self.set(bus, 1, Reg8::H),
            0xcd => self.set(bus, 1, Reg8::L),
            0xce => self.set(bus, 1, Indirect::HL),
            0xcf => self.set(bus, 1, Reg8::A),
            0xd0 => self.set(bus, 2, Reg8::B),
            0xd1 => self.set(bus, 2, Reg8::C),
            0xd2 => self.set(bus, 2, Reg8::D),
            0xd3 => self.set(bus, 2, Reg8::E),
            0xd4 => self.set(bus, 2, Reg8::H),
            0xd5 => self.set(bus, 2, Reg8::L),
            0xd6 => self.set(bus, 2, Indirect::HL),
            0xd7 => self.set(bus, 2, Reg8::A),
            0xd8 => self.set(bus, 3, Reg8::B),
            0xd9 => self.set(bus, 3, Reg8::C),
            0xda => self.set(bus, 3, Reg8::D),
            0xdb => self.set(bus, 3, Reg8::E),
            0xdc => self.set(bus, 3, Reg8::H),
            0xdd => self.set(bus, 3, Reg8::L),
            0xde => self.set(bus, 3, Indirect::HL),
            0xdf => self.set(bus, 3, Reg8::A),
            0xe0 => self.set(bus, 4, Reg8::B),
            0xe1 => self.set(bus, 4, Reg8::C),
            0xe2 => self.set(bus, 4, Reg8::D),
            0xe3 => self.set(bus, 4, Reg8::E),
            0xe4 => self.set(bus, 4, Reg8::H),
            0xe5 => self.set(bus, 4, Reg8::L),
            0xe6 => self.set(bus, 4, Indirect::HL),
            0xe7 => self.set(bus, 4, Reg8::A),
            0xe8 => self.set(bus, 5, Reg8::B),
            0xe9 => self.set(bus, 5, Reg8::C),
            0xea => self.set(bus, 5, Reg8::D),
            0xeb => self.set(bus, 5, Reg8::E),
            0xec => self.set(bus, 5, Reg8::H),
            0xed => self.set(bus, 5, Reg8::L),
            0xee => self.set(bus, 5, Indirect::HL),
            0xef => self.set(bus, 5, Reg8::A),
            0xf0 => self.set(bus, 6, Reg8::B),
            0xf1 => self.set(bus, 6, Reg8::C),
            0xf2 => self.set(bus, 6, Reg8::D),
            0xf3 => self.set(bus, 6, Reg8::E),
            0xf4 => self.set(bus, 6, Reg8::H),
            0xf5 => self.set(bus, 6, Reg8::L),
            0xf6 => self.set(bus, 6, Indirect::HL),
            0xf7 => self.set(bus, 6, Reg8::A),
            0xf8 => self.set(bus, 7, Reg8::B),
            0xf9 => self.set(bus, 7, Reg8::C),
            0xfa => self.set(bus, 7, Reg8::D),
            0xfb => self.set(bus, 7, Reg8::E),
            0xfc => self.set(bus, 7, Reg8::H),
            0xfd => self.set(bus, 7, Reg8::L),
            0xfe => self.set(bus, 7, Indirect::HL),
            0xff => self.set(bus, 7, Reg8::A),
            _ => panic!("Not implemented: cb{:02x}", self.ctx.opcode),
        }
    }

    fn call_isr(&mut self, bus: &mut Peripherals) {
        step!((), {
            0: if let Some(_) = self.push16(bus, self.regs.pc) {
                let highest_int: u8 = 1 << self.interrupts.get_interrupts().trailing_zeros();
                self.interrupts.int_flags &= !highest_int;
                self.regs.pc = match highest_int {
                    VBLANK => 0x0040,
                    STAT => 0x0048,
                    TIMER => 0x0050,
                    SERIAL => 0x0058,
                    JOYPAD => 0x0060,
                    _ => panic!("Invalid interrupt: {:02x}", highest_int),
                };
                return go!(1);
            },
            1: {
                self.interrupts.ime = false;
                go!(0);
                self.fetch(bus)
            },
        });
    }
}
